### ISSUE TITLE
Can't install in node:9-alpine

### ISSUE THREAD

**Issue by dananichev** [rolftimmermans/zeromq-ng#25]
I believe, it won't work in OS X also.
Is this project still maintained? 

```bash
node-pre-gyp ERR! Tried to download(404): https://github.com/rolftimmermans/zeromq-ng/releases/download/v5.0.0-beta.9/zeromq-ng-v5.0.0-beta.9-node-v59-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for zeromq-ng@5.0.0-beta.9 and node@9.9.0 (node-v59 ABI, musl) (falling back to source compile with node-gyp)
module.js:545
    throw err;
    ^

Error: Cannot find module 'node-addon-api'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:65:33)
    at Object.runInThisContext (vm.js:197:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:649:30)
    at evalScript (bootstrap_node.js:523:27)
gyp: Call to 'node -p "require('node-addon-api').include"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.9.60-linuxkit-aufs
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/tmp/node_modules/zeromq-ng/lib/binary/zeromq-ng.node" "--module_name=zeromq-ng" "--module_path=/tmp/node_modules/zeromq-ng/lib/binary"
gyp ERR! cwd /tmp/node_modules/zeromq-ng
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/node_modules/zeromq-ng/lib/binary/zeromq-ng.node --module_name=zeromq-ng --module_path=/tmp/node_modules/zeromq-ng/lib/binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:936:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Linux 4.9.60-linuxkit-aufs
node-pre-gyp ERR! command "/usr/local/bin/node" "/tmp/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /tmp/node_modules/zeromq-ng
node-pre-gyp ERR! node -v v9.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/node_modules/zeromq-ng/lib/binary/zeromq-ng.node --module_name=zeromq-ng --module_path=/tmp/node_modules/zeromq-ng/lib/binary' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq-ng@5.0.0-beta.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq-ng@5.0.0-beta.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-23T09_46_32_055Z-debug.log
```

**Comment by alesrebec** [comment]
Same thing as #28

**Comment by rolftimmermans** [comment]
Node 9.x versions will be supported soon. For now you can use Node 8.x – with the exception of musl based Linux such as Alpine. Support for Alpine is also coming.
