### ISSUE TITLE
install error when  python not exist

### ISSUE THREAD

**Issue by janckerchen** [rolftimmermans/zeromq-ng#30]
why depends python?  not important package should move to [optionalDependencies](https://docs.npmjs.com/files/package.json#optionaldependencies).

env:   in docker alpine image, no python installed,   maybe provid  prebuild ex for alpine linux

```
[1/1] scripts.install zeromq-ng@https://github.com/rolftimmermans/zeromq-ng.git#v5.0.0-beta.10 run "node-pre-gyp configure"
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:170:21)
gyp ERR! System Linux 4.9.87-linuxkit-aufs
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--module=/home/deploy/hume2/node_modules/_zeromq-ng@5.0.0-beta.10@zeromq-ng/lib/binary/napi-v1/zeromq-ng.node" "--module_name=zeromq-ng" "--module_path=/home/deploy/hume2/node_modules/_zeromq-ng@5.0.0-beta.10@zeromq-ng/lib/binary/napi-v1" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=1"
gyp ERR! cwd /home/deploy/hume2/node_modules/_zeromq-ng@5.0.0-beta.10@zeromq-ng
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! configure error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --module=/home/deploy/hume2/node_modules/_zeromq-ng@5.0.0-beta.10@zeromq-ng/lib/binary/napi-v1/zeromq-ng.node --module_name=zeromq-ng --module_path=/home/deploy/hume2/node_modules/_zeromq-ng@5.0.0-beta.10@zeromq-ng/lib/binary/napi-v1 --napi_version=3 --node_abi_napi=napi --napi_build_version=1' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/deploy/hume2/node_modules/_node-pre-gyp@0.9.1@node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:936:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Linux 4.9.87-linuxkit-aufs
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/deploy/hume2/node_modules/_zeromq-ng@5.0.0-beta.10@zeromq-ng/node_modules/.bin/node-pre-gyp" "configure"
node-pre-gyp ERR! cwd /home/deploy/hume2/node_modules/_zeromq-ng@5.0.0-beta.10@zeromq-ng
node-pre-gyp ERR! node -v v9.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --module=/home/deploy/hume2/node_modules/_zeromq-ng@5.0.0-beta.10@zeromq-ng/lib/binary/napi-v1/zeromq-ng.node --module_name=zeromq-ng --module_path=/home/deploy/hume2/node_modules/_zeromq-ng@5.0.0-beta.10@zeromq-ng/lib/binary/napi-v1 --napi_version=3 --node_abi_napi=napi --napi_build_version=1' (1)
Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c node-pre-gyp configure" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node-pre-gyp configure" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

```

**Comment by rolftimmermans** [comment]
A prebuilt binary for Alpine is in the works!

**Comment by janckerchen** [comment]
great job!

**Comment by rolftimmermans** [comment]
As of beta 11, a prebuilt version of Alpine should be built and released automatically.

Python is required to do source build, since `gyp` and `node-gyp` depend on it.
