### ISSUE TITLE
macOS - Build failing

### ISSUE THREAD

**Issue by affanshahid** [rolftimmermans/zeromq-ng#39]
macOS: High Sierra 10.13.5
node: 10.3.0
npm: 6.1.0

Just ran `npm i zeromq-ng`

```sh
> zeromq-ng@5.0.0-beta.9 install /Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/zeromq-ng
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/rolftimmermans/zeromq-ng/releases/download/v5.0.0-beta.9/zeromq-ng-v5.0.0-beta.9-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for zeromq-ng@5.0.0-beta.9 and node@10.3.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://github.com/rolftimmermans/zeromq-ng/releases/download/v5.0.0-beta.9/zeromq-ng-v5.0.0-beta.9-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for zeromq-ng@5.0.0-beta.9 and node@10.3.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  ACTION binding_gyp_libzmq_target_build_libzmq libzmq/lib
Downloading libzmq source...
  ACTION binding_gyp_libzmq_target_build_libzmq libzmq/lib
Downloading libzmq source...
Building libzmq...
Building libzmq...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... config/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
yes
checking whether make supports nested variables... checking for a thread-safe mkdir -p... yes
config/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... yes
checking whether make supports nested variables... yes
gnutar
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... checking whether the C compiler works... yes
yes
checking for C compiler default output file name... checking for C compiler default output file name... a.out
a.out
checking for suffix of executables... checking for suffix of executables... 

checking whether we are cross compiling... checking whether we are cross compiling... no
no
checking for suffix of object files... checking for suffix of object files... o
checking whether we are using the GNU C compiler... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking whether gcc accepts -g... yes
yes
checking for gcc option to accept ISO C89... checking for gcc option to accept ISO C89... none needed
none needed
checking whether gcc understands -c and -o together... checking whether gcc understands -c and -o together... yes
yes
checking for style of include used by make... checking for style of include used by make... GNU
GNU
checking dependency style of gcc... checking dependency style of gcc... mkdir: conftest.dir: File exists
mkdir: sub: File exists
gcc3
gcc3
checking whether C compiler accepts -std=gnu11... checking whether C compiler accepts -std=gnu11... yes
yes
checking for g++... checking for g++... g++
g++
checking whether we are using the GNU C++ compiler... checking whether we are using the GNU C++ compiler... yes
yes
checking whether g++ accepts -g... checking whether g++ accepts -g... yes
yes
checking dependency style of g++... checking dependency style of g++... mkdir: conftest.dir: File exists
mkdir: sub: File exists
gcc3
gcc3
checking whether g++ supports C++11 features by default... checking whether g++ supports C++11 features by default... mv: rename conftest.er1 to conftest.err: No such file or directory
no
no
checking whether g++ supports C++11 features with -std=gnu++11... checking whether g++ supports C++11 features with -std=gnu++11... yes
yes
checking for a sed that does not truncate output... checking for a sed that does not truncate output... mv: rename conftest.tmp to conftest.in: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: conftest.tmp: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: conftest.tmp: No such file or directory
/usr/bin/sed
/usr/bin/sed
checking whether to build with code coverage support... checking whether to build with code coverage support... no
no
checking for a sed that does not truncate output... checking for a sed that does not truncate output... (cached) (cached) /usr/bin/sed
/usr/bin/sed
checking for gawk... checking for gawk... (cached) (cached) awk
awk
checking for pkg-config... checking for pkg-config... /usr/local/bin/pkg-config
/usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... checking pkg-config is at least version 0.9.0... yes
yes
checking for xmlto... checking for xmlto... no
no
checking for asciidoc... checking for asciidoc... no
no
checking build system type... checking build system type... x86_64-apple-darwin17.6.0
x86_64-apple-darwin17.6.0
checking host system type... x86_64-apple-darwin17.6.0
checking host system type... x86_64-apple-darwin17.6.0
checking how to print strings... checking how to print strings... printf
printf
checking for a sed that does not truncate output... checking for a sed that does not truncate output... (cached) (cached) /usr/bin/sed
/usr/bin/sed
checking for grep that handles long lines and -e... checking for grep that handles long lines and -e... mv: rename conftest.tmp to conftest.in: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: conftest.tmp: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
mv: conftest.tmp: No such file or directory
mv: rename conftest.tmp to conftest.in: No such file or directory
/usr/bin/grep
checking for egrep... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
/usr/bin/grep -F
checking for ld used by gcc... checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
no
checking for BSD- or MS-compatible name lister (nm)... checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
/usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... checking the name lister (/usr/bin/nm -B) interface... BSD nm
BSD nm
checking whether ln -s works... checking whether ln -s works... yes
yes
checking the maximum length of command line arguments... checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... 196608
checking whether the shell understands some XSI constructs... yes
yes
checking whether the shell understands "+="... checking whether the shell understands "+="... yes
yes
checking how to convert x86_64-apple-darwin17.6.0 file names to x86_64-apple-darwin17.6.0 format... checking how to convert x86_64-apple-darwin17.6.0 file names to x86_64-apple-darwin17.6.0 format... func_convert_file_noop
func_convert_file_noop
checking how to convert x86_64-apple-darwin17.6.0 file names to toolchain format... checking how to convert x86_64-apple-darwin17.6.0 file names to toolchain format... func_convert_file_noop
func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
-r
checking for objdump... checking for objdump... objdump
objdump
checking how to recognize dependent libraries... checking how to recognize dependent libraries... pass_all
pass_all
checking for dlltool... checking for dlltool... dlltool
dlltool
checking how to associate runtime and link libraries... checking how to associate runtime and link libraries... printf %s\n
printf %s\n
checking for ar... checking for ar... ar
ar
checking for archiver @FILE support... checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... sed: conftest.c: No such file or directory
no
checking for sys/stat.h... yes
checking for stdlib.h... yes
failed
checking for string.h... checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
cat: conftest.err: No such file or directory
checking for memory.h... no
checking for -exported_symbols_list linker flag... mv: rename conftest.er1 to conftest.err: No such file or directory
no
no
checking for -force_load linker flag... checking for strings.h... yes
checking for inttypes.h... yes
cat: conftest.err: No such file or directory
no
checking how to run the C preprocessor... checking for stdint.h... yes
checking for unistd.h... yes
sed: conftest.c: No such file or directory
checking for dlfcn.h... cat: conftest.er1: No such file or directory
mv: rename conftest.er1 to conftest.err: No such file or directory
yes
sed: conftest.c: No such file or directory
checking for objdir... .libs
sed: conftest.c: No such file or directory
/lib/cpp
checking if gcc supports -fno-rtti -fno-exceptions... configure: error: in `/Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/zeromq-ng/build/libzmq/zeromq-4.2.2':
configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
cat: conftest.err: No such file or directory
no
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... make: *** [libzmq/lib] Error 1
gypsed: conftest.err: No such file or directory
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/affan/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/Users/affan/.nvm/versions/node/v10.3.0/bin/node" "/Users/affan/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/zeromq-ng/lib/binary/zeromq-ng.node" "--module_name=zeromq-ng" "--module_path=/Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/zeromq-ng/lib/binary"
gyp ERR! cwd /Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/zeromq-ng
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
yes
checking if gcc static flag -static works... node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/affan/.nvm/versions/node/v10.3.0/bin/node /Users/affan/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/zeromq-ng/lib/binary/zeromq-ng.node --module_name=zeromq-ng --module_path=/Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/zeromq-ng/lib/binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.6.0
node-pre-gyp ERR! command "/Users/affan/.nvm/versions/node/v10.3.0/bin/node" "/Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/zeromq-ng
node-pre-gyp ERR! node -v v10.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/affan/.nvm/versions/node/v10.3.0/bin/node /Users/affan/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/zeromq-ng/lib/binary/zeromq-ng.node --module_name=zeromq-ng --module_path=/Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/zeromq-ng/lib/binary' (1)
no
checking if gcc supports -c -o file.o... ⸨            ░░░░░░⸩ ⠋ install: info liyes          ░░░░░░⸩ ⠋ install: info lifecycle zeromq-ng@5.0.0-beta.9~install:
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... ⸨            ░░░░░░⸩ ⠋ install: info darwin17.6.0 dyld░░⸩ ⠋ install: info lifecycle zeromq-ng@5.0.0-beta.9~install:
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... ⸨            ░░░░░░⸩ ⠋ instayes info lifecycle zeromq-ng@5.0.0-beta.9~install:
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... cat: confdefs.h: No such file or directory
cat: confdefs.h: No such file or directoryycle zeromq-ng@5.0.0-beta.9~install:
g++ -std=gnu++11 -E⸩ ⠋ install: info lifecycle zeromq-ng@5.0.0-beta.9~install:
cat: confdefs.h: No such file or directory
cat: confdefs.h: No such file or directoryycle zeromq-ng@5.0.0-beta.9~install:
mv: rename conftest.er1 to conftest.err: No such file or directorya.9~install:
sed: conftest.cpp: No such file or directory
./configure: line 15162: conftest.cpp: No such file or directory
./configure: line 15163: conftest.err: No such file or directory
cat: conftest.err: No such file or directory
./configure: line 15168: conftest.cpp: No such file or directory
./configure: line 15169: conftest.err: No such file or directory
npm WARN zeromq-benchmark@1.0.0 No description
npm WARN zeromq-benchmark@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq-ng@5.0.0-beta.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq-ng@5.0.0-beta.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
cat: conftest.err: No such file or directory
checking for ld used by g++ -std=gnu++11... 
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/affan/.npm/_logs/2018-08-13T10_22_13_629Z-debug.log
Affans-MacBook-Pro:zeromq-benchmark affan$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking whether the g++ -std=gnu++11 linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
./configure: line 16396: conftest.cpp: No such file or directory
libtool.m4: error: problem compiling CXX test program
checking for g++ -std=gnu++11 option to produce PIC... -fno-common -DPIC
checking if g++ -std=gnu++11 PIC flag -fno-common -DPIC works... ./configure: line 16959: conftest.cpp: No such file or directory
./configure: line 16971: conftest.err: No such file or directory
cat: conftest.err: No such file or directory
no
checking if g++ -std=gnu++11 static flag -static works... ./configure: line 17018: conftest.cpp: No such file or directory
./configure: line 17019: conftest.err: No such file or directory
no
checking if g++ -std=gnu++11 supports -c -o file.o... mkdir: .: No such file or directory
./configure: line 17058: cd: conftest: No such file or directory
mkdir: .: No such file or directory
./configure: line 17060: conftest.cpp: No such file or directory
./configure: line 17072: out/conftest.err: No such file or directory
cat: out/conftest.err: No such file or directory
rmdir: out: No such file or directory
./configure: line 17092: cd: ..: No such file or directory
no
checking if g++ -std=gnu++11 supports -c -o file.o... (cached) no
checking whether the g++ -std=gnu++11 linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin17.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking for valgrind... no
checking whether the C compiler works... ./configure: line 18489: conftest.c: No such file or directory
./configure: line 1751: conftest.err: No such file or directory
sed: conftest.c: No such file or directory
no
configure: error: Unable to find a working C compiler
make: *** [libzmq/lib] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/affan/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/Users/affan/.nvm/versions/node/v10.3.0/bin/node" "/Users/affan/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/zeromq-ng/lib/binary/zeromq-ng.node" "--module_name=zeromq-ng" "--module_path=/Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/zeromq-ng/lib/binary"
gyp ERR! cwd /Users/affan/Playgrounds/NodePlaygrounds/zeromq-benchmark/node_modules/zeromq-ng
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

```

**Comment by rolftimmermans** [comment]
Prebuilt versions for Node 10 are now available as of beta 11.

**Comment by affanshahid** [comment]
It was due to Node 10, since I downgraded to 8.6 and it worked great. Ill try it out again

**Comment by affanshahid** [comment]
Working with Node 10.8.0 as now
